sudo: required
dist: trusty
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libqt4-dev libpthread-stubs0-dev libusb-dev libjpeg-dev texlive-font-utils
    - sudo apt-get install -qq cfitsio-dev doxygen graphviz libavcodec-dev libavformat-dev libavutil-dev libsdl1.2-dev
script:
    - cmake ./CMakeLists.txt
    - make
    - make package_source
    - make package
    - sudo make install
