include ../Makefile.vars

PROG=qastrocam-g2
TMP_DESTDIR=../bin
OBJ_QT =
OBJ_cpp = main.o
OBJ_asm =
OBJ_c =

OTHERINC=-I../qastrolib
OTHERLIB=-L../lib -lqastro

EXTERNAL_DEPENDENCIES=../lib/libqastro.a

include ../Makefile.common
