# Qastrocam
# Copyright (C) 2003-2009   Franck Sicard
# Qastrocam-g2
# Copyright (C) 2009   Blaise-Florentin Collin

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.

include ../Makefile.vars

PROG=qastrocam-g2
TMP_DESTDIR=../bin
OBJ_QT =
OBJ_cpp = main.o
OBJ_asm =
OBJ_c =

OTHERINC=-I../qastrolib
OTHERLIB=-L../lib -lqastro

EXTERNAL_DEPENDENCIES=../lib/libqastro.a

include ../Makefile.common
